In [1]:
import cv2
c = cv2.VideoCapture(r"C:\Users\cidzerda\Documents\GitHub\streams\nikolarn.mp4", cv2.CAP_MSMF)
_, frame = c.read()

In [2]:
part = frame[450:450 + 3, 88:88 + 88]
print(min(part.reshape(-1)))
print(part.argmin())
print(part.reshape(-1)[part.argmin()])
cv2.imshow('tesst', frame)
cv2.imshow('part', part)
cv2.waitKey(0)

229
144
229


96

In [3]:
print(part.shape, part)
print(part.mean(0).shape, part.mean(0))
print(part.mean(0).mean(1).shape, part.mean(0).mean(1))
#print(dir(part))
help(part.sum)

(3, 88, 3) [[[253 255 242]
  [253 255 242]
  [253 255 242]
  [253 255 242]
  [253 255 242]
  [253 255 243]
  [253 255 243]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [253 254 245]
  [252 253 244]
  [252 253 244]
  [251 252 243]
  [250 251 242]
  [249 250 240]
  [248 248 239]
  [248 248 239]
  [248 248 239]
  [248 248 239]
  [248 248 239]
  [248 248 239]
  [248 248 239]
  [248 248 239]
  [248 248 239]
  [248 248 239]
  [248 248 239]
  [246 249 239]
  [244 249 239]
  [240 249 241]
  [236 250 241]
  [234 250 241]
  [232 251 241]
  [232 251 241]
  [232 251 241]
  [232 251 241]
  [232 252 239]
  [232 252 239]
  [229 253 238]
  [229 253 238]
  [229 254 236]
  [229 254 236]
  [229 254 236]
  [232 253 236]
  [233 254 237]
  [235 254 237]
  [235 255 236]
  [238 255 237]
  [238 255 237]
  [238 255 237]
  [238 255 237]
  [240 254 23

In [4]:
c.release()
cv2.destroyAllWindows()